### ISSUE TITLE
[Feat] Timer Page 수정

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#10]
## TODO
* [x] 정지 버튼 삭제
* [x] Timer 시작 버튼 클릭 시 오른쪽 아래 창 띄우기 + 고정 기능 추가
* [ ] Timer 시작 버튼 클릭 시 Pomodoro 시작 X
* [ ] Timer 시작 버튼 클릭 시 모달 창 ("이미 공부 시간이 측정 되고 있어요!")

## 문구 추가
* [ ] 목표 시간 달성 시 "오늘의 공부 목표량을 달성했어요!" 문구 추가
* [ ] 목표 달성 시 "목표를 전부 완료했어요!" 문구 추가
* [x] "4시 기준으로 업데이트 돼요!" 문구 추가
