### ISSUE TITLE
[Feat] Home Page

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#13]
## TODO
* [x] Home Page Calendar 추가
* [x] Home Page Study Time 추가
* [x] Home Page CSS
* [ ] Home Page 반응형 구현
