### ISSUE TITLE
[Feat] 전체 구조 변경

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#14]
## TODO
* [x] content 구조 변경

## 반응형 웹 구현
* [x] header css 수정
* [x] header 반응형 구현
* [x] nav bar 가로 정렬 -> 세로 정렬
* [x] nav bar 위치 변경 (header, content, nav bar)
