### ISSUE TITLE
[Feat] TotalStudy 컴포넌트 분리

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#18]
## TODO
* [x] TotalStudy 컴포넌트 분리
* [x] CSS 조정
* [x] TODO Page 설명 추가
* [x] TODO Page 설명 css 수정
