### ISSUE TITLE
[Feat] 반응형 웹 (모바일) CSS 수정

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#20]
## TODO
* [x] nav bar css 수정
* [x] Header css 수정

## 컴포넌트 크기 조정
* [x] Home 컴포넌트 크기 조정
* [x] Timer 컴포넌트 크기 조정
* [x] ToDoList 컴포넌트 크기 조정
