### ISSUE TITLE
[Feat] 버튼 클릭 이벤트 추가

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#29]
## TODO
* [x] DB에 저장된 시간 보여주기
* [x] 현재 시간 저장

## Timer
* [x] start 함수 구현
* [x] stop 함수 구현
