### ISSUE TITLE
[Feat] 일일 통계 파트 DB 연결

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#32]
## TODO
* [x] 값 변경 or stop 버튼 이벤트 발생 시 일일 통계 파트 업데이트
* [x] 제목 변경 (기준: 날짜)
* [x] 공부 시간이 0 이상이면 날짜 색 변경 (디폴트 값 - 회색, 공부 - 검은색)
* [x] 컬렉션이 null인 경우 default 값 == 0
* [x] timer 업데이트 시 날짜에 따른 일일 통계 파트 시간 업데이트

## Timer
* [x] 날짜 확인 로직 추가
