### ISSUE TITLE
[Feat] Timer DB 연결

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#36]
## TODO
* [x] 날짜에 따른 시간 저장 기능 구현
* [x] 컬렉션이 null인 경우 생성
* [x] 날짜 (오늘)에 맞춰 타이머 시간 불러오기
* [x] 저장된 시간이 없을 경우 0으로 타이머 초기화

## ToDoList
* [x] 시간 업데이트 문구 수정
