### ISSUE TITLE
[Feat] Home CSS 수정

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2023-Colog#8]
## TODO
* [x] Start Button CSS 추가
* [x] nav Bar CSS 수정
* [x] url에 따른 단어 색 변경
* [x] Header 반응형 구현

## STUDY
* [x] 창 고정
